ALTER TABLE "User"
ADD COLUMN "phone" TEXT,
ADD COLUMN "dateOfBirth" DATE,
ADD COLUMN "gender" TEXT NOT NULL DEFAULT 'Nam',
ADD COLUMN "country" TEXT NOT NULL DEFAULT 'Việt Nam',
ADD COLUMN "level" "LevelType" NOT NULL DEFAULT 'HSK3',
ADD COLUMN "learning_goal" TEXT NOT NULL DEFAULT 'Giao tiếp',
ADD COLUMN "daily_target" INTEGER NOT NULL DEFAULT 20;
